import Nav from '@/components/dashboard/nav/nav';
import SidebarDashboard from '@/components/dashboard/side-bar/side-bar';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function DasboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen flex">
      <SidebarDashboard />
      <div className="flex-1 p-4">
        <Nav />
        <div className="flex mb-6 mt-4">
          <div className="flex-1 h-1 bg-dodger-blue-500"></div>
          <div className="flex-1 h-1 bg-golden-dream-500"></div>
          <div className="flex-1 h-1 bg-apple-500"></div>
        </div>
        {children}
      </div>
    </main>
  );
}
