import type { Metadata } from "next";
import "./globals.css";
import SessionAuthProvider from "../contexts/SessionAuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="">
        <SessionAuthProvider>{children}</SessionAuthProvider>
      </body>
    </html>
  );
}
