import type { Metadata } from "next";
import "./globals.css";
import SessionAuthProvider from "../contexts/SessionAuthProvider";
import ReactQueryProvider from "@/lib/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="">
        <SessionAuthProvider>
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
