import Nav from "@/components/home/nav/nav";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Recursos Humanos Nandayure",
    description: "Generated by create next app",
};


export default function HomeLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="min-h-screen">
            <Nav />
            {children}
        </main>
    );
}