import Nav from '@/components/dashboard/nav/nav';
import { SideBarProfile } from '@/components/profile/side-bar/side-bar';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Profile',
  description: 'Generated by create next app',
};

export default function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen flex">
      <SideBarProfile />
      <div className="flex-1 p-4">
        <Nav />
        {children}
      </div>
    </main>
  );
}
